### ISSUE TITLE
Any equivalent step by step turorial with Azure AD B2C ? ²

### ISSUE THREAD

**Issue by LaurentTermeau** [MicrosoftDocs/bot-docs.fr-fr#2]
I'd like to implement a User authentication in BotFramework using DotNetCore and Bot Framework V4 on Azure AD B2C so that a user can sign in with its preferred social network provider (Facebook, LinkedIn, twitter , etc... ) . 
I've tried to apply some of the concepts presented in this article as well as other samples from GitHub but with no success so far, and I'm struggling to set this up. 
Any help or guidance would be great, thanks. 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: a9a43e68-83a3-1adc-0c55-e277ddb98c6b
* Version Independent ID: 5c46848d-bc20-480e-4571-00a283d930a2
* Content: [Ajouter l’authentification à votre bot par le biais d’Azure Bot Service - Bot Service](https://docs.microsoft.com/fr-fr/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv1%2Ccsharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-authentication.md](https://github.com/MicrosoftDocs/bot-docs.fr-fr/blob/live/articles/v4sdk/bot-builder-authentication.md)
* Service: **bot-service**
* Sub-service: **abs**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **v-jofing**

**Comment by CeciAc** [comment]
Hello, @LaurentTermeau

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
